(defun convert ()
(format t "Enter Fahrenheit ")
  (LET (fahrenheit)
    (SETQ fahrenheit (read fahrenheit))     
          (LET (celsius) 
               (SETQ celsius (round(*(- fahrenheit 32.0)(/ 5.0 9.0))) )   
               (format t "Celsius is ~a" celsius)   
               (if (<= celsius 0) (format t " Pack Long Underwear ~C" #\linefeed))
               (if(>= fahrenheit 100) (format t " Remember to Hydrate ~C"  #\linefeed))
          )
  )
  (format t "~C"  #\linefeed)
  (format t "Would you like to do another calculation? 1=yes 2=no ")
  (LET (repeat)
     (SETQ repeat (read repeat))
          (if (= repeat 1) (convert))
)